// Drizzle owns SQL generation. This gate verifies its artifacts and immutable history.
import { execFileSync } from "node:child_process";
import { readFile, readdir, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { isDeepStrictEqual } from "node:util";
import { createJiti } from "jiti";

const require = createRequire(import.meta.url);
const { generateDrizzleJson, generateMigration } = require("drizzle-kit/api");
export const watermark = "-- @generated by pnpm db generate (Drizzle Kit). Do not edit by hand.\n";

export class MigrationArtifactError extends Error {
  constructor(code, detail) {
    super(`${code}: ${detail}`);
    this.code = code;
    this.name = "MigrationArtifactError";
  }
}

export function parseJournal(value) {
  if (value?.dialect !== "postgresql" || value.version !== "7" || !Array.isArray(value.entries) || !value.entries.length) {
    throw new MigrationArtifactError("invalid_history", "expected a PostgreSQL v7 journal");
  }
  let timestamp = -1;
  for (const [index, entry] of value.entries.entries()) {
    if (entry?.idx !== index || entry.version !== "7" || entry.breakpoints !== true ||
      !Number.isSafeInteger(entry.when) || entry.when <= timestamp ||
      typeof entry.tag !== "string" || !new RegExp(`^${String(index).padStart(4, "0") }_[a-z0-9_]+$`).test(entry.tag)) {
      throw new MigrationArtifactError("invalid_history", `invalid journal entry ${index}`);
    }
    timestamp = entry.when;
  }
  return value.entries;
}

export async function readHistory(root) {
  const directory = join(root, "drizzle");
  const entries = parseJournal(JSON.parse(await readFile(join(directory, "meta/_journal.json"), "utf8")));
  const expected = entries.map((entry) => `${entry.tag}.sql`).sort();
  const actual = (await readdir(directory)).filter((name) => name.endsWith(".sql")).sort();
  const snapshots = (await readdir(join(directory, "meta"))).filter((name) => name.endsWith("_snapshot.json")).sort();
  if (!isDeepStrictEqual(actual, expected) || !isDeepStrictEqual(snapshots, entries.map(snapshotName))) {
    throw new MigrationArtifactError("invalid_history", "SQL, snapshots, and journal must match one-to-one");
  }
  const history = [];
  for (const entry of entries) {
    const snapshotBytes = await readFile(join(directory, "meta", snapshotName(entry)), "utf8");
    history.push({ entry, snapshotBytes, snapshot: JSON.parse(snapshotBytes),
      sql: await readFile(join(directory, `${entry.tag}.sql`), "utf8") });
  }
  return history;
}

function snapshotName(entry) {
  return `${String(entry.idx).padStart(4, "0")}_snapshot.json`;
}

function body(sql) {
  return sql.startsWith(watermark) ? sql.slice(watermark.length) : sql;
}

function assertUnambiguousDelta(previous, current) {
  // Drizzle's public diff API prompts for simultaneous creations and removals.
  // Lint and CI must fail rather than wait for an interactive rename decision.
  const pairs = ["schemas", "tables", "enums", "sequences", "roles", "policies", "views"]
    .map((key) => [previous[key] ?? {}, current[key] ?? {}, key]);
  for (const name of Object.keys(previous.tables)) {
    if (Object.hasOwn(current.tables, name)) {
      for (const key of ["columns", "policies"]) {
        pairs.push([previous.tables[name][key] ?? {}, current.tables[name][key] ?? {}, `${name}.${key}`]);
      }
    }
  }
  for (const [before, after, label] of pairs) {
    if (Object.keys(before).some((key) => !Object.hasOwn(after, key)) && Object.keys(after).some((key) => !Object.hasOwn(before, key))) {
      throw new MigrationArtifactError("rename_resolution_required", `${label}: split unrelated additions/removals; renames need an explicit noninteractive verifier`);
    }
  }
}

function schemaContent(snapshot) {
  const { id: _id, prevId: _prevId, _meta, ...content } = snapshot;
  return JSON.parse(JSON.stringify(content));
}

async function declaredSnapshot(root, previousId) {
  const jiti = createJiti(import.meta.url, { moduleCache: false, fsCache: false });
  const config = await jiti.import(join(root, "drizzle.config.ts"), { default: true });
  if (config.dialect !== "postgresql" || config.out !== "./drizzle" || typeof config.schema !== "string") {
    throw new MigrationArtifactError("invalid_config", "expected the canonical PostgreSQL schema and output");
  }
  return generateDrizzleJson(await jiti.import(join(root, config.schema)), previousId);
}

function checkCommittedHistory(root, history, baseRef) {
  const git = (...args) => execFileSync("git", args, { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
  const revision = git("rev-parse", "--verify", "--end-of-options", `${baseRef}^{commit}`).trim();
  const prefix = `${git("rev-parse", "--show-prefix").trim()}drizzle/`;
  const files = git("ls-tree", "-r", "--full-tree", "--name-only", revision).trim().split("\n");
  if (!files.includes(`${prefix}meta/_journal.json`)) {
    throw new MigrationArtifactError("invalid_base", "base must contain this database's migration history");
  }
  const previous = parseJournal(JSON.parse(git("show", `${revision}:${prefix}meta/_journal.json`)));
  for (const entry of previous) {
    const current = history[entry.idx];
    if (!current || !isDeepStrictEqual(current.entry, entry) ||
      body(current.sql) !== body(git("show", `${revision}:${prefix}${entry.tag}.sql`)) ||
      current.snapshotBytes !== git("show", `${revision}:${prefix}meta/${snapshotName(entry)}`)) {
      throw new MigrationArtifactError("history_rewritten", entry.tag);
    }
  }
}

export async function checkMigrations(root, { schema = true, allowMissingWatermark = false, baseRef = "HEAD" } = {}) {
  const history = await readHistory(root);
  checkCommittedHistory(root, history, baseRef);
  let previous = { ...generateDrizzleJson({}), id: "00000000-0000-0000-0000-000000000000" };
  const ids = new Set([previous.id]);
  for (const migration of history) {
    const { snapshot, sql, entry } = migration;
    if (snapshot.prevId !== previous.id || ids.has(snapshot.id)) {
      throw new MigrationArtifactError("invalid_history", `broken snapshot chain at ${entry.tag}`);
    }
    // Drizzle validates the full snapshot shape before regenerating any SQL.
    assertUnambiguousDelta(previous, snapshot);
    const generated = (await generateMigration(previous, snapshot)).join("--> statement-breakpoint\n");
    if (!generated || body(sql) !== generated) throw new MigrationArtifactError("sql_drift", entry.tag);
    if (!allowMissingWatermark && !sql.startsWith(watermark)) {
      throw new MigrationArtifactError("missing_watermark", entry.tag);
    }
    ids.add(snapshot.id);
    previous = snapshot;
  }
  if (schema) {
    const current = await declaredSnapshot(root, previous.id);
    if (!isDeepStrictEqual(schemaContent(previous), schemaContent(current))) {
      throw new MigrationArtifactError("schema_drift", "run pnpm db generate --name=describe_change");
    }
  }
  return history;
}

export async function generateMigrations(root, name, options = {}) {
  if (!/^[a-z][a-z0-9_]*$/.test(name)) throw new MigrationArtifactError("invalid_name", name);
  const history = await checkMigrations(root, { ...options, schema: false });
  const previous = history.at(-1).snapshot;
  const current = await declaredSnapshot(root, previous.id);
  if (isDeepStrictEqual(schemaContent(previous), schemaContent(current))) return;
  assertUnambiguousDelta(previous, current);
  const binary = join(dirname(require.resolve("drizzle-kit/api")), "bin.cjs");
  execFileSync(process.execPath, [binary, "generate", `--name=${name}`], { cwd: root, stdio: "inherit" });
  await stampMigrations(root, options);
}

export async function stampMigrations(root, options = {}) {
  const history = await checkMigrations(root, { ...options, allowMissingWatermark: true });
  for (const migration of history) {
    if (!migration.sql.startsWith(watermark)) {
      await writeFile(join(root, "drizzle", `${migration.entry.tag}.sql`), watermark + migration.sql);
    }
  }
}
