/** Header adoption must not replay applied SQL or rewrite Drizzle's recorded history. */
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { generateDrizzleJson, generateMigration } from "drizzle-kit/api";
import { sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { pgTable, text } from "drizzle-orm/pg-core";
import { Pool } from "pg";
import { expect, it } from "vitest";

it("annotating an applied migration preserves its ledger and data", async () => {
  const connectionString = process.env["TEST_DATABASE_URL"];
  if (!connectionString) throw new Error("TEST_DATABASE_URL must name a disposable PostgreSQL database");
  const directory = await mkdtemp(join(tmpdir(), "pizza-watermark-"));
  const suffix = crypto.randomUUID().replaceAll("-", "");
  const table = pgTable(`watermark_${suffix}`, { id: text("id").primaryKey() });
  const migrationsSchema = `journal_${suffix}`;
  const pool = new Pool({ connectionString });
  const db = drizzle(pool);
  const configuration = { migrationsFolder: directory, migrationsSchema };
  try {
    const statements = await generateMigration(generateDrizzleJson({}), generateDrizzleJson({ table }));
    const original = statements.join("--> statement-breakpoint\n");
    await mkdir(join(directory, "meta"));
    await writeFile(join(directory, "0000_fixture.sql"), original);
    await writeFile(join(directory, "meta/_journal.json"), JSON.stringify({
      version: "7", dialect: "postgresql",
      entries: [{ idx: 0, version: "7", when: 1000, tag: "0000_fixture", breakpoints: true }],
    }));
    await migrate(db, configuration);
    await db.insert(table).values({ id: "preserved" });
    const ledger = sql`select id, hash, created_at from ${sql.identifier(migrationsSchema)}.__drizzle_migrations order by id`;
    const before = await db.execute(ledger);
    const current = await readFile(new URL("../../drizzle/0000_postgres.sql", import.meta.url), "utf8");
    const header = current.slice(0, current.indexOf("\n") + 1);
    expect(header).toContain("-- @generated by pnpm db generate");
    await writeFile(join(directory, "0000_fixture.sql"), header + original);
    await migrate(db, configuration);
    expect((await db.execute(ledger)).rows).toEqual(before.rows);
    expect(await db.select().from(table)).toEqual([{ id: "preserved" }]);
  } finally {
    try {
      await db.execute(sql`drop table if exists ${table}`);
      await db.execute(sql`drop schema if exists ${sql.identifier(migrationsSchema)} cascade`);
    } finally {
      await pool.end();
      await rm(directory, { recursive: true, force: true });
    }
  }
});
