import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { execFileSync } from "node:child_process";
import { createRequire } from "node:module";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";
import { checkMigrations, generateMigrations, stampMigrations } from "../apps/pizza/scripts/migrations.mjs";

const require = createRequire(new URL("../apps/pizza/package.json", import.meta.url));
const { generateDrizzleJson, generateMigration } = require("drizzle-kit/api");
const { pgTable, text, pgPolicy } = require("drizzle-orm/pg-core");
const { sql: sqlExpression } = require("drizzle-orm");
const { createJiti } = require("jiti");
const empty = { ...generateDrizzleJson({}), id: "00000000-0000-0000-0000-000000000000" };

const watermark = "-- @generated by pnpm db generate (Drizzle Kit). Do not edit by hand.\n";
const migrations = new URL("../apps/pizza/drizzle/", import.meta.url);

test("every migration identifies its generator", async () => {
  for (const name of (await readdir(migrations)).filter((name) => name.endsWith(".sql"))) {
    const sql = await readFile(new URL(name, migrations), "utf8");
    assert.ok(sql.startsWith(watermark), `${name} lacks its generated watermark`);
  }
});

async function fixture(t, policy = false) {
  const root = await mkdtemp(join(tmpdir(), "pizza-migrations-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  await mkdir(join(root, "drizzle/meta"), { recursive: true });
  const core = require.resolve("drizzle-orm/pg-core");
  const policySource = policy ? ', () => [pgPolicy("old_policy", {for:"select",to:"public",using:sql`true`})]' : "";
  const source = `import { pgTable, text, pgPolicy } from ${JSON.stringify(core)};\nimport { sql } from ${JSON.stringify(require.resolve("drizzle-orm"))};\nexport const items = pgTable("items", {id: text("id").primaryKey()}${policySource});\n`;
  await writeFile(join(root, "schema.ts"), source);
  await writeFile(join(root, "drizzle.config.ts"), 'export default {dialect:"postgresql",out:"./drizzle",schema:"./schema.ts"};');
  const snapshot = generateDrizzleJson({ items: pgTable("items", { id: text("id").primaryKey() }, () =>
    policy ? [pgPolicy("old_policy", { for: "select", to: "public", using: sqlExpression`true` })] : []) });
  const sql = (await generateMigration(empty, snapshot)).join("--> statement-breakpoint\n");
  const entry = { idx: 0, version: "7", when: 1000, tag: "0000_items", breakpoints: true };
  const journal = { dialect: "postgresql", version: "7", entries: [entry] };
  await writeFile(join(root, "drizzle/meta/0000_snapshot.json"), JSON.stringify(snapshot));
  await writeFile(join(root, "drizzle/meta/_journal.json"), JSON.stringify(journal));
  await writeFile(join(root, "drizzle/0000_items.sql"), sql);
  const git = (...args) => execFileSync("git", args, { cwd: root, stdio: "pipe" });
  git("init", "-q");
  git("add", ".");
  // Fixture commits must not invoke the user's repository or global hooks.
  git("-c", "core.hooksPath=/dev/null", "-c", "user.name=Migration Tests", "-c", "user.email=tests@example.invalid", "-c", "commit.gpgsign=false", "commit", "-qm", "fixture");
  return { root, source, snapshot, sql, journal };
}

test("watermark adoption preserves SQL bodies and is idempotent", async (t) => {
  const { root, sql } = await fixture(t);
  await assert.rejects(checkMigrations(root), { code: "missing_watermark" });
  await stampMigrations(root);
  await checkMigrations(root);
  const path = join(root, "drizzle/0000_items.sql");
  assert.equal(await readFile(path, "utf8"), watermark + sql);
  await stampMigrations(root);
  assert.equal(await readFile(path, "utf8"), watermark + sql);
});

test("a watermark cannot bless changed SQL or rewritten history", async (t) => {
  const { root, sql } = await fixture(t);
  await writeFile(join(root, "drizzle/0000_items.sql"), watermark + sql + "\nSELECT 1;");
  await assert.rejects(checkMigrations(root), { code: "history_rewritten" });
  await assert.rejects(stampMigrations(root), { code: "history_rewritten" });
});

test("schema changes require a new generated migration", async (t) => {
  const { root, source } = await fixture(t);
  await stampMigrations(root);
  await writeFile(join(root, "schema.ts"), source.replace('id: text("id").primaryKey()', 'id: text("id").primaryKey(), name: text("name")'));
  await assert.rejects(checkMigrations(root), { code: "schema_drift" });
});

test("new SQL must agree exactly with Drizzle's snapshot delta", async (t) => {
  const { root, snapshot, journal } = await fixture(t);
  await stampMigrations(root);
  const next = generateDrizzleJson({ items: pgTable("items", { id: text("id").primaryKey(), name: text("name") }) }, snapshot.id);
  journal.entries.push({ ...journal.entries[0], idx: 1, when: 2000, tag: "0001_name" });
  await writeFile(join(root, "drizzle/meta/_journal.json"), JSON.stringify(journal));
  await writeFile(join(root, "drizzle/meta/0001_snapshot.json"), JSON.stringify(next));
  await writeFile(join(root, "drizzle/0001_name.sql"), watermark + "SELECT 1;");
  await assert.rejects(checkMigrations(root), { code: "sql_drift" });
});

test("unregistered SQL and broken journal ordering are rejected", async (t) => {
  const { root, journal } = await fixture(t);
  await stampMigrations(root);
  const orphan = join(root, "drizzle/0001_unregistered.sql");
  await writeFile(orphan, watermark + "SELECT 1;");
  await assert.rejects(checkMigrations(root), { code: "invalid_history" });
  await rm(orphan);
  journal.entries[0].idx = 2;
  await writeFile(join(root, "drizzle/meta/_journal.json"), JSON.stringify(journal));
  await assert.rejects(checkMigrations(root), { code: "invalid_history" });
});

test("unavailable comparison bases fail closed", async (t) => {
  const { root } = await fixture(t);
  await stampMigrations(root);
  await assert.rejects(checkMigrations(root, { baseRef: "missing-revision" }));
});

test("generation appends marked SQL without rewriting existing artifacts", async (t) => {
  const { root, source, sql } = await fixture(t);
  await stampMigrations(root);
  await writeFile(join(root, "schema.ts"), source.replace('id: text("id").primaryKey()', 'id: text("id").primaryKey(), name: text("name")'));
  await generateMigrations(root, "add_name");
  const history = await checkMigrations(root);
  assert.equal(history.length, 2);
  assert.equal(await readFile(join(root, "drizzle/0000_items.sql"), "utf8"), watermark + sql);
  assert.ok(history[1].sql.startsWith(watermark));
  await generateMigrations(root, "no_change");
  assert.equal((await checkMigrations(root)).length, 2);
});

test("ambiguous renames fail instead of prompting in automation", async (t) => {
  const { root, source } = await fixture(t);
  await stampMigrations(root);
  await writeFile(join(root, "schema.ts"), source.replace('pgTable("items"', 'pgTable("renamed"'));
  await assert.rejects(generateMigrations(root, "rename_items"), { code: "rename_resolution_required" });
});

for (const [kind, policy, from, to] of [
  ["prototype-named columns", false, 'id: text("id").primaryKey()', 'renamed: text("constructor").primaryKey()'],
  ["table policies", true, 'pgPolicy("old_policy"', 'pgPolicy("new_policy"'],
]) {
  test(`automation rejects ambiguous changes to ${kind}`, async (t) => {
    const { root, source } = await fixture(t, policy);
    await stampMigrations(root);
    await writeFile(join(root, "schema.ts"), source.replace(from, to));
    await assert.rejects(generateMigrations(root, "ambiguous_change"), { code: "rename_resolution_required" });
  });
}

test("deployment validates history against the pre-push revision", async () => {
  const jiti = createJiti(import.meta.url);
  const { deploy } = await jiti.import(fileURLToPath(new URL("../gha/deploy.ts", import.meta.url)));
  const steps = deploy.jobs.deploy.steps;
  assert.equal(steps.find((step) => step.uses?.startsWith("actions/checkout@"))?.with?.["fetch-depth"], 0);
  assert.equal(steps.find((step) => step.run === "pnpm db migrate")?.env?.MIGRATION_BASE_REF, "${{ github.event.before }}");
});

test("automation cannot silently validate against its own HEAD", () => {
  assert.throws(() => execFileSync(process.execPath, [
    fileURLToPath(new URL("../apps/pizza/scripts/db.mjs", import.meta.url)), "check",
  ], { env: { ...process.env, GITHUB_ACTIONS: "true", MIGRATION_BASE_REF: "" }, stdio: "pipe" }),
  (error) => error.status === 1 && error.stderr.toString().includes("missing_base_ref"));
});
