/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false` (hash: b32ef977eda325a0b702fcab3aaa3ed9)
interface __BaseEnv_Env {
	HYPERDRIVE: Hyperdrive;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	BETTER_AUTH_URL: string;
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_ADMIN_USER_IDS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/app");
	}
	interface DevEnv {
		HYPERDRIVE: Hyperdrive;
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
		BETTER_AUTH_URL: string;
		BETTER_AUTH_SECRET: string;
		BETTER_AUTH_ADMIN_USER_IDS: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "BETTER_AUTH_URL" | "BETTER_AUTH_SECRET" | "BETTER_AUTH_ADMIN_USER_IDS">> {}
}
